train:
  seed: 0
  total_steps: 200
  max_episode_steps: 200
  log_interval: 100
  save_interval: 1000
  eval_interval: 5000
  eval_episodes: 2
  record_interval: 100
  device: cpu
env:
  type: dmcontrol
  name: cartpole_swingup
  domain_name: cartpole
  task_name: swingup
  observation:
    type: image
    num_cams: 1
  action:
    clip: true
    normalize: true
  render:
    enabled: true
    save_frames: true
    save_video: false
    height: 240
    width: 320
    camera_id: 0
  isaac:
    task_name: null
    num_envs: 1
    headless: true
    create_cam: null
policy:
  type: mlp
  name: mlp_baseline
  checkpoint:
    load: false
    path: null
    save: false
